apiVersion: v1
kind: Service
metadata:
  name: psmdb-metrics
  namespace: mongodb
  labels:
    app: psmdb-metrics-eyego
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '9216'
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: http-metrics
    port: 9216
    targetPort: 9216
    protocol: TCP
  selector:
    app.kubernetes.io/instance: my-db
    app.kubernetes.io/name: percona-server-mongodb
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: psmdb-metrics-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - mongodb
  selector:
    matchLabels:
      app: psmdb-metrics-eyego
  endpoints:
  - port: http-metrics
    interval: 15s