apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: main-rules
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: monitoring
spec:
  groups: 
  - name: main.rules
    rules:
# creating alert rule for host high cpu load
    - alert: HostHighCpuLoad
      expr: |
        100 - (
          avg by (nodename) (
            rate(node_cpu_seconds_total{mode="idle"}[2m]) * 100
            * on(instance) group_left(nodename) 
            node_uname_info
          )
        ) > 70
      for: 2m
      labels:
        severity: warning
        namespace: monitoring
      annotations:
        description: "High CPU load detected on node {{ $labels.nodename }} in namespace monitoring. Current CPU load is {{ $value }}%."
        summary: "High CPU load detected on node {{ $labels.nodename }} in namespace monitoring."
# create another alert rule for kube-pod-container failure and keep restarts morethan 5 restarts
    - alert: KubePodContainerFailure
      expr: kube_pod_container_status_restarts_total > 3
      for: 0m
      labels:
        severity: critical
        namespace: monitoring
      annotations:
        description: "Container {{ $labels.container_name }} in pod {{ $labels.pod_name }} has restarted {{ $value }} times."
        summary: "Container {{ $labels.container_name }} in pod {{ $labels.pod_name }} crash looping."

    - alert: KubeImagePullBackOff
      expr: kube_pod_container_status_waiting_reason{reason=~"ImagePullBackOff|ErrImagePull"} == 1
      for: 2m
      labels:
        severity: warning
        namespace: monitoring
      annotations:
        summary: "Image pull failure for pod {{ $labels.pod }}"
        description: "Container {{ $labels.container }} in pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is failing to pull its image."

    - alert: HostHighMemoryUsage
      expr: |
        (
          (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100
          * on(instance) group_left(nodename)
          node_uname_info
        ) > 90
      for: 2m
      labels:
        severity: critical
        namespace: monitoring
      annotations:
        description: "High memory usage detected on node {{ $labels.nodename }}. Current memory usage is {{ $value }}%."
        summary: "High memory usage detected on node {{ $labels.nodename }}."

    - alert: KubePodOOMKilled
      expr: increase(kube_pod_container_status_restarts_total{reason="OOMKilled"}[5m]) > 0
      for: 0m
      labels:
        severity: critical
        namespace: monitoring
      annotations:
        description: "Container {{ $labels.container }} in pod {{ $labels.pod }} in namespace {{ $labels.namespace }} was OOMKilled."
        summary: "Pod {{ $labels.pod }} OOMKilled in namespace {{ $labels.namespace }}."

  - name: mongodb.rules
    rules:
      - alert: MongoDBDown
        expr: |
          # No mongodb_up samples in the last 5 minutes => likely down / missing scrape
          (count_over_time(mongodb_up[5m]) == 0)
          or
          # All observed mongodb_up series are 0 (only evaluate if any series exist)
          ((count(mongodb_up) > 0) and (max without(job) (mongodb_up) == 0))
        for: 0m
        labels:
          severity: critical
          namespace: monitoring
        annotations:
          description: "MongoDB {{ $labels.service_name }} on {{ $labels.node_name }} is down."
          summary: "MongoDB down ({{ $labels.service_name }})"

      - alert: mongodb_replset_no_primary
        expr: avg(mongodb_ss_repl_isWritablePrimary) by(cluster,rs_nm) == 0
        for: 0m
        labels:
          severity: critical
          namespace: monitoring
        annotations:
          description: "MongoDB has NO Primary for ReplSet {{ $labels.rs_nm }} in {{ $labels.cluster }} cluster.."
          summary: "MongoDB has NO Primary for ReplSet ({{ $labels.rs_nm }})"
      
      - alert: mongodb_replset_primary_changed
        expr: min by (set)(changes(mongodb_mongod_replset_my_state[10m]) > 0)
        for: 0m
        labels:
          severity: warning
          namespace: monitoring
        annotations:
          description: "Replica set {{ $labels.set }} has undergone a primary change in the last 10 minutes"
          summary: "Primary changed in {{ $labels.set }}"

      - alert: mongodb_unusual_state
        expr: group(mongodb_rs_members_state != 1 and mongodb_rs_members_state != 2 and mongodb_rs_members_state != 7 and mongodb_rs_members_state != 8) by (cluster,member_idx,member_state,rs_nm)
        for: 0m
        labels:
          severity: warning
          namespace: monitoring
        annotations:
          description: "MongoDB replicaSet member ({{ $labels.member_idx }}) is in \"{{ $labels.member_state }}\" state for cluster {{ $labels.cluster }}."
          summary: "MongoDB replicaSet member is in unusual state for ({{ $labels.member_idx }})"

      - alert: mongodb_high_memory_usage
        expr: |
          (
            sum by (node_name, service_name) (mongodb_ss_mem_resident * 1024 * 1024)
            /
            clamp_min(sum by (node_name) (node_memory_MemTotal_bytes), 1)
          ) * 100 > 80
        for: 0m
        labels:
          severity: warning
          namespace: monitoring
        annotations:
          description: "{{ $value }}% of memory (more than 80%) is used by {{ $labels.service_name }} on {{ $labels.node_name }}."
          summary: "MongoDB high memory usage ({{ $labels.service_name }})"

      - alert: mongodb_restarted
        expr: |
          # Prefer detecting restarts by observing a change in the start time
          (changes(mongodb_instance_start_time_seconds[5m]) > 0)
          or
          # Fallback when start_time metric is not present: very low uptime observed
          (
            count(mongodb_instance_start_time_seconds) == 0
            and
            mongodb_instance_uptime_seconds < 300
          )
        for: 1m
        labels:
          severity: warning
          namespace: monitoring
        annotations:
          description: "MongoDB {{ $labels.service_name }} on {{ $labels.node_name }} was restarted recently."
          summary: "MongoDB restarted ({{ $labels.service_name }})"